####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-upscaling
Description: DUNE module containing single-phase and steady-state upscaling methods
Version: 2017.04-pre
Label: 2017.04-pre
Maintainer: arne.morten.kvarving@sintef.no
MaintainerName: Arne Morten Kvarving
Url: http://opm-project.org
Depends: dune-common dune-grid dune-istl opm-grid opm-common
