####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-upscaling
Description: DUNE module containing single-phase and steady-state upscaling methods
Version: 2020.10
Label: 2020.10
Maintainer: arne.morten.kvarving@sintef.no
MaintainerName: Arne Morten Kvarving
Url: http://opm-project.org
Depends: dune-common (>= 2.6) dune-grid (>= 2.6) dune-istl (>= 2.6) opm-common opm-grid
