####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-upscaling
Description: DUNE module containing single-phase and steady-state upscaling methods
Version: 2023.10-rc1
Label: 2023.10-rc1
Maintainer: arne.morten.kvarving@sintef.no
MaintainerName: Arne Morten Kvarving
Url: http://opm-project.org
Depends: dune-common (>= 2.7) dune-grid (>= 2.7) dune-istl (>= 2.7) opm-common opm-grid
