.TH CPREGULARIZE "29" "April 2021" "cpregularize 2020.04" "User Commands"
.SH NAME
cpregularize \- Program to regularize cornerpoint grids
.SH SYNOPSIS
cpregularize gridfilename=cornerpointgrid.grdecl [option=value]
.SH DESCRIPTION
Program to regularize cornerpoint grids. Caveats:
- Only grids with vertical pillars
- CornerPointChopper can only chop along existing pillars. In case your asked-for horizontal resolution does not divide the initial number of pillars in x/y, you will not obtain a fully regular grid, but still easier numerically.
- Be careful with non-flat top and bottom boundary.

Example usage:

cpregularize gridfilename=grid.grdecl ires=5 jres=5 zres=5 resultgrid=regularizedgrid.grdecl
.SH OPTIONS
\fB\resultgrid\fR File name for regular grid.
\fB\ires\fR Resolution in i-direction. Defaults to 1.
\fB\jres\fR Resolution in j-direction. Defaults to 1.
\fB\zres\fR Resolution in z-direction. Defaults to 1.
\fB\imin\fR Can be used to limit the search area for random subsamples. Defaults to minimum i in inputgrid (full model).
\fB\imax\fR Can be used to limit the search area for random subsamples. Defaults to maximum i in inputgrid (full model).
\fB\jmin\fR Analog to imin, but in j-direction. Defaults to minimum j in inputgrid (full model).
\fB\jmax\fR Analog to imax, but in j-direction. Defaults to maximum j in inputgrid (full model).
\fB\zmin\fR Analog to imin, but in z-direction and specified in the grids length unit. Defaults to minimum in inputgrid.
\fB\zmax\fR Analog to imax, but in z-direction and specified in the grids length unit. Defaults to maximum in inputgrid.
\fB\minperm\fR Cut-off value for permeability.
.SH "REPORTING BUGS"
Report on github repository <https://github.com/OPM/opm-upscaling/issues>
.SH "SEE ALSO"
upscale_perm
