.TH UPSCALE_AVG "29" "April 2021" "upscale_avg 2020.04" "User Commands"
.SH NAME
upscale_avg \- Upscale using simple averages and report statistics
.SH SYNOPSIS
upscale_avg gridfilename=cornerpointgrid.grdecl [option=value]
.SH DESCRIPTION
Upscale using simple averages and report statistics.

Example usage:

upscale_avg -use_actnum gridfilename=grid.grdecl
.SH OPTIONS
\fB\-use_actnum\fR Only take averages over active cells.
.SH "REPORTING BUGS"
Report on github repository <https://github.com/OPM/opm-upscaling/issues>
